services:
  prime-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prime-worker
    env_file:
      - .env
    restart: unless-stopped
    network_mode: host
    mem_limit: 256m
