version: "2.4"

services:
  prime-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prime-worker
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8081:8081"
    mem_limit: 256m
