app:
  google:
    spreadsheet-id: ${SPREADSHEET_ID}
  bybit:
      api-key: ${BYBIT_API_KEY}
      api-secret: ${BYBIT_API_SECRET}
      recv-window: 5000

spring:
  application:
    name: PrimeWorker
